reference_genome: ../resources/reference/GCA_937616625.1_ddMerAnnu1.1_genomic.fna
fastq_path: /users/jgerchen/scratch/qtl/1A/fastq
temp_files: /users/jgerchen/scratch/qtl/1A/tmp
user_input: /users/jgerchen/scratch/qtl/1A/user_input
cross_name: 1A
stacks_dir: ../resources/software/stacks-2.62
stacks_out: /users/jgerchen/scratch/qtl/1A/stacks_out
stats_dir: /users/jgerchen/scratch/qtl/1A/stats
vcf_dir: /users/jgerchen/scratch/qtl/1A/vcf
lep_dir: /users/jgerchen/scratch/qtl/1A/lm
male_grandparent: 1A_F0_P
female_grandparent: 1A_F0_M
F1: 1A_F1
lepmap_bin: ../resources/software/lepmap/bin
phenotypes: /users/jgerchen/scratch/qtl/1A/user_input/1A_rqtl.phen
