reference_genome: ../resources/reference/GCA_937616625.1_ddMerAnnu1.1_genomic.fna
fastq_path: /users/jgerchen/scratch/qtl/5A/fastq
temp_files: /users/jgerchen/scratch/qtl/5A/tmp
user_input: /users/jgerchen/scratch/qtl/5A/user_input
cross_name: 5A
stacks_dir: ../resources/software/stacks-2.62
stacks_out: /users/jgerchen/scratch/qtl/5A/stacks_out
stats_dir: /users/jgerchen/scratch/qtl/5A/stats
vcf_dir: /users/jgerchen/scratch/qtl/5A/vcf
lep_dir: /users/jgerchen/scratch/qtl/5A/lm
male_grandparent: 5A_F0_P
female_grandparent: 5A_P0_F
F1: 5A_F1
lepmap_bin: ../resources/software/lepmap/bin
phenotypes: /users/jgerchen/scratch/qtl/5A/user_input/5A_rqtl.phen
