reference_genome: ../resources/reference/GCA_937616625.1_ddMerAnnu1.1_genomic.fna
fastq_path: /users/jgerchen/scratch/qtl/S1/fastqs/S1_all
temp_files: /users/jgerchen/scratch/qtl/S1/tmp
user_input: /users/jgerchen/scratch/qtl/S1/user_input
cross_name: S1
stacks_dir: ../resources/software/stacks-2.62
stacks_out: /users/jgerchen/scratch/qtl/S1/stacks_out
stats_dir: /users/jgerchen/scratch/qtl/S1/stats
vcf_dir: /users/jgerchen/scratch/qtl/S1/vcf
lep_dir: /users/jgerchen/scratch/qtl/S1/lm
male_grandparent: S1_F0_P
female_grandparent: S1_F0_M
F1: S1_F1
lepmap_bin: ../resources/software/lepmap/bin
phenotypes: /users/jgerchen/scratch/qtl/S1/user_input/S1_rqtl.phen
